get:
	curl -H "Content-Type=application/json" http://localhost:4001/posts/123/comments 

post:
	curl -XPOST -H "Content-Type: application/json" -d '{ "content": "I am a comment" }'  http://localhost:4001/posts/123/comments

post2:
	curl -XPOST -H "Content-Type: application/json" -d '{ "content": "Second comment" }'  http://localhost:4001/posts/123/comments